version: '3'
services:
  mongoM1:
    image: arm64v8/mongo
    ports:
      - 27017:27017
    environment:
      MONGO_SERVER: admin
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb:/data/db

  mongo:
    image: arm64v8/mongo
    ports:
      - 27017:27017
    environment:
      MONGO_SERVER: admin
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb:/data/db

  # tactictrade-api:

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

volumes:
 mongodb:
