# Generated by Django 4.0.3 on 2022-04-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trading_config',
            name='quantityQTYLong',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='trading_config',
            name='quantityQTYShort',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
