# Generated by Django 4.0.4 on 2022-05-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trading_config',
            name='stopLossLongUsd',
            field=models.FloatField(blank=True, default=-3, null=True),
        ),
        migrations.AddField(
            model_name='trading_config',
            name='takeProfitLongUsd',
            field=models.FloatField(blank=True, default=10, null=True),
        ),
    ]
