# Generated by Django 4.0.3 on 2022-04-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='long_allowed_fractional',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='long_allowed_fractional_crypto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='long_is_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='long_is_allowed_crypto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='short_allowed_fractional',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='short_allowed_fractional_crypto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='short_is_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='short_is_allowed_crypto',
            field=models.BooleanField(default=True),
        ),
    ]
