# Generated by Django 4.0.4 on 2022-04-25 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0001_initial'),
        ('strategy', '0001_initial'),
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paper_trading', models.BooleanField(blank=True, default=True, null=True)),
                ('order', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='sell', max_length=255)),
                ('operation', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], default='long', max_length=255)),
                ('qty_open', models.FloatField(blank=True, default=0, null=True)),
                ('qty_close', models.FloatField(blank=True, default=0, null=True)),
                ('price_open', models.FloatField(blank=True, default=0, null=True)),
                ('price_closed', models.FloatField(blank=True, default=0, null=True)),
                ('base_cost', models.FloatField(blank=True, default=0, null=True)),
                ('close_cost', models.FloatField(blank=True, default=0, null=True)),
                ('amount_open', models.FloatField(blank=True, default=0, null=True)),
                ('amount_close', models.FloatField(blank=True, default=0, null=True)),
                ('spread', models.FloatField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('opened', 'opened'), ('success', 'success'), ('close', 'close'), ('pending', 'pending'), ('error', 'error'), ('close_pending', 'close_pending'), ('accepted_alpaca', 'accepted_alpaca'), ('transactions_updated_calculate_profit', 'transactions_updated_calculate_profit')], default='closed', max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isClosed', models.BooleanField(default=False)),
                ('stop_loss', models.FloatField(blank=True, default=-1, null=True)),
                ('stop_loss_qty', models.FloatField(blank=True, default=-1, null=True)),
                ('take_profit', models.FloatField(blank=True, default=-1, null=True)),
                ('take_profit_qty', models.FloatField(blank=True, default=-1, null=True)),
                ('is_winner', models.BooleanField(default=False)),
                ('broker_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('number_stock', models.FloatField(blank=True, default=0, null=True)),
                ('closeType', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('canceled', 'Canceled'), ('accepted', 'Accepted')], default='automatic', max_length=255)),
                ('idTransaction', models.CharField(blank=True, max_length=255, null=True)),
                ('last_status', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('profit', models.FloatField(blank=True, default=0, null=True)),
                ('profit_percentage', models.FloatField(blank=True, default=0, null=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.broker')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('strategyNews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.strategynews')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.symbolstrategy')),
                ('trading_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.trading_config')),
            ],
        ),
    ]
