# Generated by Django 4.0.4 on 2022-05-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='close_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
