# Generated by Django 4.0.3 on 2022-04-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='amount_close',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='amount_open',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='spread',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('opened', 'opened'), ('success', 'success'), ('close', 'close'), ('pending', 'pending'), ('error', 'error'), ('close_pending', 'close_pending')], default='closed', max_length=255),
        ),
    ]
