# Generated by Django 4.0.3 on 2022-04-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transactions_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('opened', 'opened'), ('success', 'success'), ('close', 'close'), ('pending', 'pending'), ('error', 'error'), ('close_pending', 'close_pending'), ('accepted_alpaca', 'accepted_alpaca'), ('transactions_updated_calculate_profit', 'transactions_updated_calculate_profit')], default='closed', max_length=255),
        ),
    ]
