# Generated by Django 4.0.3 on 2022-04-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_transactions_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='stop_loss_qty',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='take_profit_qty',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
    ]
