# Generated by Django 4.0.4 on 2022-04-24 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(choices=[('theme', 'Theme'), ('generals', 'General')], default='generals', max_length=60)),
                ('theme', models.CharField(blank=True, choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=60, null=True)),
                ('language', models.CharField(choices=[('es', 'ES'), ('en', 'EN'), ('fr', 'FR'), ('de', 'DE'), ('it', 'IT'), ('pt', 'PT'), ('ru', 'RU'), ('zh', 'ZH')], default='en', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
