# Generated by Django 4.0.4 on 2022-04-27 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(choices=[('notifications_push_long', 'Receive Long Notifications Push'), ('notifications_push_short', 'Receive Short Notifications Push'), ('language', 'Language')], max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bool_value', models.BooleanField(default=True)),
                ('string_value', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('is_switch_on', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
