# Generated by Django 4.0.4 on 2022-04-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='family',
            field=models.CharField(choices=[('notifications', 'Notifications')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
