# Generated by Django 4.0.4 on 2022-04-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_setting_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='family',
            field=models.CharField(choices=[('Notifications', 'notifications'), ('Test', 'test')], max_length=100),
        ),
        migrations.AlterField(
            model_name='setting',
            name='icon',
            field=models.CharField(blank=True, default='0xf03c3', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='setting',
            field=models.CharField(choices=[('Receive Long Notifications Push', 'notifications_push_long'), ('Receive Short Notifications Push', 'notifications_push_short'), ('language', 'Language'), ('TestOption', 'Test Option')], max_length=100, unique=True),
        ),
    ]
