# Generated by Django 4.0.4 on 2022-04-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_alter_setting_family_alter_setting_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='feature_flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('family', models.CharField(blank=True, max_length=100, null=True)),
                ('localization', models.CharField(blank=True, max_length=100, null=True)),
                ('family_id', models.CharField(blank=True, max_length=100, null=True)),
                ('flag_open', models.BooleanField(default=True)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('version_app', models.CharField(blank=True, max_length=100, null=True)),
                ('is_production', models.BooleanField(default=True)),
                ('is_staging', models.BooleanField(default=True)),
                ('is_development', models.BooleanField(default=True)),
            ],
        ),
    ]
