# Generated by Django 4.0.4 on 2022-04-29 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_feature_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature_flag',
            name='is_development',
        ),
        migrations.RemoveField(
            model_name='feature_flag',
            name='is_production',
        ),
        migrations.RemoveField(
            model_name='feature_flag',
            name='is_staging',
        ),
    ]
