# Generated by Django 4.0.4 on 2022-05-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_remove_feature_flag_is_development_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='setting',
            field=models.CharField(choices=[('Receive Long Notifications Push', 'notifications_push_long'), ('Receive Short Notifications Push', 'notifications_push_short'), ('language', 'Language'), ('TestOption', 'Test Option')], max_length=100),
        ),
    ]
