# Generated by Django 4.0.4 on 2022-05-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_alter_setting_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='family',
            field=models.CharField(choices=[('Notifications', 'notifications'), ('Language', 'language'), ('Test', 'test')], max_length=100),
        ),
    ]
