# Generated by Django 4.0.4 on 2022-04-25 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(blank=True, choices=[('open_long_buy', 'open_long_buy'), ('close_long_sell', 'close_long_sell'), ('open_short_buy', 'open_short_buy'), ('open_short_sell', 'open_short_sell')], max_length=60, null=True)),
                ('title', models.CharField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=255)),
                ('priority', models.CharField(default='high', max_length=20)),
                ('image', models.CharField(default='', max_length=255)),
                ('navigate_to', models.CharField(blank=True, choices=[('strategy', 'strategy'), ('news', 'news'), ('profile', 'profile')], default='', max_length=60, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_trade', models.BooleanField(default=False)),
                ('is_winner', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
