# Generated by Django 4.0.4 on 2022-04-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='isClosed',
            field=models.BooleanField(default=False),
        ),
    ]
