# Generated by Django 4.0.4 on 2022-04-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_notification_transact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='symbol',
            field=models.CharField(default='', max_length=20),
        ),
    ]
