# Generated by Django 4.0.4 on 2022-04-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_notification_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='strategyName',
            field=models.CharField(default='', max_length=40),
        ),
    ]
