# Generated by Django 4.0.4 on 2022-04-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_notification_strategyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='base_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='base_price',
            field=models.FloatField(default=0),
        ),
    ]
