# Generated by Django 4.0.4 on 2022-04-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_notification_base_cost_notification_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='operation',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='order',
            field=models.CharField(default='', max_length=10),
        ),
    ]
