# Generated by Django 4.0.4 on 2022-04-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_notification_operation_notification_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='profit',
            field=models.FloatField(default=0),
        ),
    ]
