# Generated by Django 4.0.3 on 2022-04-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategynews',
            name='strategyNews',
            field=models.CharField(max_length=60),
        ),
    ]
