# Generated by Django 4.0.3 on 2022-04-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_alter_strategynews_strategynews'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbolstrategy',
            name='is_crypto',
            field=models.BooleanField(default=False),
        ),
    ]
