# Generated by Django 4.0.4 on 2022-05-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_alter_strategynews_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategynews',
            name='period',
            field=models.CharField(blank=True, choices=[('minute', 'minute'), ('hour', 'hour'), ('day', 'day'), ('week', 'week'), ('year', 'year')], default='hours', max_length=60, null=True),
        ),
    ]
