# Generated by Django 4.0.4 on 2022-05-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_alter_strategynews_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategynews',
            name='pusher',
            field=models.CharField(blank=True, choices=[('https://s3.tradingview.com/userpics/6171439-Hlns_big.png', 'TradingView'), ('https://ik.imagekit.io/tactictrade/IconIALogo_A29Qe98TSX.png?ik-sdk-version=javascript-1.4.3&updatedAt=1653761986425', 'TacticTradeIA')], default='tradingview', max_length=200, null=True),
        ),
    ]
