# Generated by Django 4.0.4 on 2022-04-24 11:44

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alpaca_configuration',
            name='SecretKey',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=50)),
        ),
    ]
